### ISSUE TITLE
Stack trace emitted when selecting skills

### ISSUE THREAD

**Issue by doctor-g** [studio-368/monsters#69]
I have not rigorously tried to reproduce this, but I've seen it twice.

java.lang.NullPointerException
	at edu.bsu.storygame.core.view.PlayerCreationGroup.checkForCompletion(PlayerCreationGroup.java:82)
	at edu.bsu.storygame.core.view.PlayerCreationGroup.access$000(PlayerCreationGroup.java:40)
	at edu.bsu.storygame.core.view.PlayerCreationGroup$2.onAdd(PlayerCreationGroup.java:70)
	at edu.bsu.storygame.core.view.PlayerCreationGroup$2.onAdd(PlayerCreationGroup.java:67)
	at react.RList$Listener.onAdd(RList.java:27)
	at react.RList$3.notify(RList.java:318)
	at react.Reactor.notify(Reactor.java:139)
	at react.RCollection.notify(RCollection.java:52)
	at react.RList.emitAdd(RList.java:300)
	at react.RList.add(RList.java:125)
	at react.RList.add(RList.java:118)
	at edu.bsu.storygame.core.view.BiSelector$2.onEmit(BiSelector.java:86)
	at edu.bsu.storygame.core.view.BiSelector$2.onEmit(BiSelector.java:79)
	at react.Slot.onChange(Slot.java:58)
	at react.AbstractValue$4.notify(AbstractValue.java:189)
	at react.Reactor.notify(Reactor.java:139)
	at react.AbstractValue.notifyChange(AbstractValue.java:176)
	at react.AbstractValue.emitChange(AbstractValue.java:169)
	at react.AbstractValue.updateAndNotify(AbstractValue.java:160)
	at react.AbstractValue.updateAndNotifyIf(AbstractValue.java:139)
	at react.Value.update(Value.java:34)
	at tripleplay.ui.Behavior$Toggle.onPress(Behavior.java:125)
	at tripleplay.ui.Behavior.onStart(Behavior.java:337)
	at playn.scene.Pointer$Listener.onEmit(Pointer.java:46)
	at react.AbstractSignal$3.notify(AbstractSignal.java:65)
	at react.Reactor.notify(Reactor.java:139)
	at react.AbstractSignal.notifyEmit(AbstractSignal.java:60)
	at react.Signal.emit(Signal.java:25)
	at playn.scene.Interaction.dispatch(Interaction.java:141)
	at playn.scene.Interaction.dispatch(Interaction.java:125)
	at playn.scene.Pointer$Dispatcher.onEmit(Pointer.java:87)
	at playn.scene.Pointer$Dispatcher.onEmit(Pointer.java:68)
	at react.AbstractSignal$3.notify(AbstractSignal.java:65)
	at react.Reactor.notify(Reactor.java:139)
	at react.AbstractSignal.notifyEmit(AbstractSignal.java:60)
	at react.Signal.emit(Signal.java:25)
	at playn.core.Platform.dispatchEvent(Platform.java:110)
	at playn.core.Pointer.forward(Pointer.java:115)
	at playn.core.Pointer$2.onEmit(Pointer.java:102)
	at playn.core.Pointer$2.onEmit(Pointer.java:93)
	at react.AbstractSignal$3.notify(AbstractSignal.java:65)
	at react.Reactor.notify(Reactor.java:139)
	at react.AbstractSignal.notifyEmit(AbstractSignal.java:60)
	at react.Signal.emit(Signal.java:25)
	at playn.core.Platform.dispatchEvent(Platform.java:110)
	at playn.core.Input.emitMouseButton(Input.java:143)
	at playn.java.LWJGLInput.update(LWJGLInput.java:100)
	at playn.java.JavaPlatform.processFrame(JavaPlatform.java:184)
	at playn.java.LWJGLPlatform.loop(LWJGLPlatform.java:64)
	at playn.java.JavaPlatform.start(JavaPlatform.java:141)
	at edu.bsu.storygame.java.MonsterGameJava.main(MonsterGameJava.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by doctor-g** [comment]
@krittichier and I have confirmed that it can be reproduced by deselecting regions--especially the left player, but sometimes the right too.
